name: Java CI with Gradle

on:
  push:
    branches: [ "origin/Auth" ]
  pull_request:
    branches: [ "origin/Auth" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.12.1'

    - name: Build with Gradle Wrapper
      run: ./server/gradlew build  # 경로를 수정했습니다.

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.12.1'

    - name: Generate and submit dependency graph
      run: ./server/gradlew dependencyInsight  # 경로를 수정했습니다.
